### PR TITLE
Created Changelog and updated docstring for evaluate script

### PR DESCRIPTION
**Pull request by Aishwarya120111**
I have created the changelog and updated docstring for evaluate script. Kindly review the changes and let me know your feedback.

### CODE REVIEW

**Comment by Jing-19** [comment]
I think it might be more helpful to add a few sentences about the improvements that we have made.

For the EDA part please add: "We added a descriptive plot title to both EDA distribution plots to make it easier for the audiences to understand. To further improve the readability, I removed the 'year' subplot to make the message more clear that we have a skewed distribution for all the energy consumption features."

**Comment by Jing-19** [comment]
@WeilinHan8 Please a sentence or two description of changes you made on the report about data for the changelog! Thanks.

**Comment by WeilinHan8** [comment]
@Aishwarya120111  could you please update changelog by adding following content in updating ipynb part:
Adding raw data description to provide details of CO2 emission, energy consumption and energy generation datasets. Updating data wrangling rationale and showing the final processed dataset that used for modeling.

**Review by WeilinHan8 — CHANGES_REQUESTED** [review]
please see above suggestion

**Comment by Aishwarya120111** [comment]
I have made the requested changes...Kindly verify it

**Review by tonyshumlh — APPROVED** [review]

**Pull request merged**
