### PR TITLE
update contributing.md and docstring

### PR DESCRIPTION
**Pull request by WeilinHan8**
Hi team, I have updated the docstring for data_fetch_clean.py and update contributing.md regarding peer review suggestions. Please let me know if you have any concerns

### CODE REVIEW

**Review by Aishwarya120111 — CHANGES_REQUESTED** [review]
From the feedback we are asked to write the steps for issue creation as well. Could you please add that also.

**Comment by WeilinHan8** [comment]
@Aishwarya120111  I have update Contributing.md

**Review by Jing-19 — COMMENTED** [review]
There are some small typos like "projdect" in the first line, please fix them. Everything else looks good, thanks!

**Review by Aishwarya120111 — APPROVED** [review]

**Review by tonyshumlh — APPROVED** [review]
Looks good

**Pull request merged**
