### PR TITLE
Merged the code, saved and plotted the results, evaluated metrics

### PR DESCRIPTION
**Pull request by Aishwarya120111**
I have merged code and modified few cells. I have added evaluations metrics and plots for model.
Kindly review the code and let me know if anything else need to changed.

### CODE REVIEW

**Comment by tonyshumlh** [comment]
@Aishwarya120111 It looks nice! Except that I found there are some codes that are out of the boundary in the HTML file. You may want to help format the codes

**Comment by Aishwarya120111** [comment]
> @Aishwarya120111 It looks nice! Except that I found there are some codes that are out of the boundary in the HTML file. You may want to help format the codes

Yeah will check the codes and do the formatting so that it prompts well in HTML report.

**Comment by WeilinHan8** [comment]
looks good to me, thank you for changing the directory path in data wrangling part!

**Review by Jing-19 — COMMENTED** [review]
Thanks for putting everything together! I have reviewed the changes, and please ensure all the plots are displayed in the notebook and html (I notice there are couples of plots are not showing in the EDA section). Everthing else looks pretty good! Good work team!

**Review by tonyshumlh — APPROVED** [review]
Look Good to us :)

**Pull request merged**
